wordpress:
  build: .
  links:
    - db
  ports:
    - 8189:80
  environment:
      - WORDPRESS_WP_DEBUG=false
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_PORT=3366
db:
  image: mariadb
  ports:
      - "3366:3306"
  environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=db